version: "3"

services:
  backend:
    build: .
    command: bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
