version: "3"

volumes:
  postgres_volume:

services:
  backend:
    build: .
    command: bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
        postgres:

  socket:
    build: socket_service
    command: npm start
    restart: unless-stopped
    volumes:
      - ./socket_service:/chatsocket
      - /chatsocket/node_modules
    ports:
      - "9000:9000"
    networks:
      - postgres

  db:
    build: db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
        postgres:
    ports:
      - "5433:5432"

networks:
  postgres:
    driver: bridge
